### ISSUE TITLE
 createTTG.py Code 

### ISSUE THREAD

**Issue by 464hee** [Henrik86/Topological-tumour-graphs#2]
I am unable to complete the reproduction and request help.
Why the output of createTTG.py does not have the important feature of your paper: the (stromal clustering and stromal barrier).
But these two features (stromal clustering and stromal barrier) appear again in TTG_data.
Please explain the reproduction calculation parameters for these two parameters in the reproducible code.

**Comment by 464hee** [comment]
@Henrik86 @sathyam89

**Comment by Henrik86** [comment]
Sorry for the confusion:

stromal barrier refers to _avgShortestPathsLymCancer_ in the code.

stromal clustering refers to _clusteringStromal_ in the code.

**Comment by 464hee** [comment]
> 对困惑感到抱歉：
> 
> 基质屏障是指代码中的_avgShortestPathsLymCancer_。
> 
> stromal clustering是指代码中的_clusteringStromal_。

Thank you for your reply
