### ISSUE TITLE
Found that the method of calculating Stromal_barrier in the code does not match the paper

### ISSUE THREAD

**Issue by 464hee** [Henrik86/Topological-tumour-graphs#4]
#########The stromal barrier explained in your article####
 B, The corresponding TTG, in which cancer cell nodes have been summarized to a cancer supernode, whereas each of the lymphocyte/stromal node represent a single lymphocyte/stromal cell. The number of stromal nodes on the shortest path from a lymphocyte to the nearest cancer supernode was calculated and later averaged to derive the quantitative measure of stromal barrier.
###################

but in TTG.py code  343-351
In your code, why is the path of the lymphocyte node to the cancerCluster set to 1?
According to the description in your paper,The lymphocyte-connected cancerCluster should not be included in the calculation of the stromal barrier ah

Because they have no stromal nodes

**Comment by 464hee** [comment]
@Henrik86

**Comment by Henrik86** [comment]
The number of stromal nodes, should be _path_length_ -1
